services:
  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: "book"
      MYSQL_ROOT_PASSWORD: "12345678"
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "mysql",
          "-u",
          "root",
          "-p12345678",
        ]
      interval: 5s
      timeout: 10s
      retries: 5
  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - mysql
    command: /bin/sh -c "sleep 40; uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000

  client:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      - NEXT_PUBLIC_BASEURL=http://127.0.0.1:8000/books
    ports:
      - 3000:3000
